[package]
name = "meilisearch-importer"
version = "0.1.0"
edition = "2021"

[dependencies]
byte-unit = { version = "5.1.4", features = ["byte", "serde"] }
csv = "1.3.0"
flate2 = "1.0"
indicatif = "0.17.8"
reqwest = { version = "0.11.26", default-features = false, features = ["rustls-tls"] }
serde_json = { version = "1.0.114", features = ["preserve_order"] }
structopt = "0.3.26"
tokio = { version = "1.36.0", features = ["full"] }
tokio-retry = "0.3.0"
